# Generated by Django 5.2.5 on 2025-08-11 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la banque')),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Type de contrat')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Type de document')),
            ],
        ),
        migrations.CreateModel(
            name='PieceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Type de pièce')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro de compte bancaire'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name="Nom et prénom du contact d'urgence"),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name="Téléphone du contact d'urgence"),
        ),
        migrations.AddField(
            model_name='user',
            name='eritop_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Eritop'),
        ),
        migrations.AddField(
            model_name='user',
            name='isignum',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numéro Isignum'),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email personnel'),
        ),
        migrations.AddField(
            model_name='user',
            name='piece_number',
            field=models.CharField(blank=True, max_length=100, verbose_name="Numéro de la pièce d'identité"),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email professionnel'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.bankinfo', verbose_name='Nom de la banque'),
        ),
        migrations.AddField(
            model_name='user',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.contracttype', verbose_name='Type de contrat'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.documenttype', verbose_name='Type de document'),
        ),
        migrations.AddField(
            model_name='user',
            name='piece_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.piecetype', verbose_name="Type de pièce d'identité"),
        ),
    ]
