# Generated by Django 5.2.5 on 2025-08-11 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_bankinfo_contracttype_documenttype_piecetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_urgence',
        ),
        migrations.RemoveField(
            model_name='user',
            name='informations_bancaires',
        ),
        migrations.AddField(
            model_name='profileupdate',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profileupdate',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro de compte bancaire'),
        ),
        migrations.AddField(
            model_name='profileupdate',
            name='bank_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.bankinfo', verbose_name='Nom de la banque'),
        ),
        migrations.AddField(
            model_name='profileupdate',
            name='cnss',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro CNSS/Sécurité Sociale'),
        ),
        migrations.AddField(
            model_name='profileupdate',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.contracttype', verbose_name='Type de contrat'),
        ),
        migrations.AddField(
            model_name='profileupdate',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileupdate',
            name='dependants',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profileupdate',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name="Nom et prénom du contact d'urgence"),
        ),
        migrations.AddField(
            model_name='profileupdate',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name="Téléphone du contact d'urgence"),
        ),
        migrations.AddField(
            model_name='profileupdate',
            name='eritop_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Eritop'),
        ),
        migrations.AddField(
            model_name='profileupdate',
            name='isignum',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numéro Isignum'),
        ),
        migrations.AddField(
            model_name='profileupdate',
            name='maladies_chroniques',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profileupdate',
            name='medicaments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profileupdate',
            name='nationalite',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profileupdate',
            name='pays_de_naissance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profileupdate',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email personnel'),
        ),
        migrations.AddField(
            model_name='profileupdate',
            name='piece_number',
            field=models.CharField(blank=True, max_length=100, verbose_name="Numéro de la pièce d'identité"),
        ),
        migrations.AddField(
            model_name='profileupdate',
            name='piece_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.piecetype', verbose_name="Type de pièce d'identité"),
        ),
        migrations.AddField(
            model_name='profileupdate',
            name='professional_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email professionnel'),
        ),
        migrations.AddField(
            model_name='profileupdate',
            name='type_sanguin',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name="Rôle de l'emploi"),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.jobrole'),
        ),
    ]
