# Generated by Django 5.2.5 on 2025-08-11 20:56

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_remove_user_contact_urgence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileupdate',
            name='nationalite',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='profileupdate',
            name='pays_de_naissance',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationalite',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='pays_de_naissance',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
