# Generated by Django 5.2.5 on 2025-08-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_alter_profileupdate_nationalite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileupdate',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profils_updates/'),
        ),
    ]
