# Generated by Django 5.2.5 on 2025-08-14 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0005_profileupdate_photo_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du badge')),
                ('description', models.TextField(verbose_name='Description du badge')),
                ('icon', models.CharField(help_text="Nom d'une icône CSS (ex: 'fa-star')", max_length=50, verbose_name='Icône')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Couleur du badge (code hexa)')),
            ],
            options={
                'verbose_name': 'Définition de badge',
                'verbose_name_plural': 'Définitions de badges',
            },
        ),
        migrations.CreateModel(
            name='EmployeeBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'attribution")),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.badgedefinition', verbose_name='Badge attribué')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_badges', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': "Badge d'employé",
                'verbose_name_plural': 'Badges des employés',
                'unique_together': {('employee', 'badge')},
            },
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
