# Generated by Django 5.2.5 on 2025-08-20 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0006_badgedefinition_employeebadge_delete_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du pays')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Code ISO 3166-1 alpha-2')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.country', verbose_name="Pays de l'employé"),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_countries',
            field=models.ManyToManyField(blank=True, related_name='managers', to='intranet.country', verbose_name='Pays gérés'),
        ),
    ]
