# Generated by Django 5.2.5 on 2025-08-26 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0007_country_user_country_user_managed_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la période')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Période active')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire de base')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire brut')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire net')),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impôts')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Déductions')),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Primes et bonus')),
                ('other_payments', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Autres paiements')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='intranet.payperiod', verbose_name='Période de paie')),
            ],
            options={
                'unique_together': {('employee', 'pay_period')},
            },
        ),
    ]
