# Generated by Django 5.2.5 on 2025-08-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0010_documentrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'Type de document', 'verbose_name_plural': 'Types de documents'},
        ),
        migrations.AddField(
            model_name='documenttype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='template_name',
            field=models.CharField(default='intranet/documents_pdf/attestation_travail.html', help_text='attestation_travail.html', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom du document'),
        ),
    ]
