# Generated by Django 5.2.5 on 2025-08-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0012_documenttype_country_specific_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='country_specific',
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='template_name',
            field=models.CharField(help_text='attestation_travail.html', max_length=255),
        ),
    ]
