# Generated by Django 5.2.5 on 2025-08-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0013_remove_documenttype_country_specific_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='country_specific',
            field=models.BooleanField(default=False, verbose_name='Spécifique à un pays'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='template_name',
            field=models.CharField(help_text='Nom du fichier de gabarit HTML pour ce document (ex: attestation_travail.html)', max_length=255),
        ),
    ]
