# Generated by Django 5.2.5 on 2025-09-03 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0015_event_notification_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du projet')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description du projet')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin estimée')),
                ('status', models.CharField(choices=[('À FAIRE', 'À faire'), ('EN COURS', 'En cours'), ('TERMINÉ', 'Terminé')], default='À FAIRE', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Coordinateur du projet')),
                ('team_members', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name="Membres de l'équipe")),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du site')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localisation')),
                ('site_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Identifiant unique du site')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='intranet.project', verbose_name='Projet associé')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Titre de l'activité")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Description de l'activité")),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('status', models.CharField(choices=[('À FAIRE', 'À faire'), ('EN COURS', 'En cours'), ('TERMINÉ', 'Terminé'), ('EN ATTENTE', 'En attente')], default='À FAIRE', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='intranet.site', verbose_name='Site associé')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
            },
        ),
    ]
