# Generated by Django 5.2.5 on 2025-09-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0016_project_site_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileupdate',
            name='updated_fields',
            field=models.JSONField(default=dict, verbose_name='Champs mis à jour'),
        ),
    ]
