# Generated by Django 5.2.5 on 2025-09-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0017_profileupdate_updated_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileupdate',
            name='rejection_comments',
            field=models.JSONField(blank=True, null=True, verbose_name='Commentaires de rejet'),
        ),
    ]
