# Generated by Django 5.2.5 on 2025-09-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0018_profileupdate_rejection_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lien'),
        ),
        migrations.AlterField(
            model_name='profileupdate',
            name='rejection_comments',
            field=models.JSONField(blank=True, default=dict, verbose_name='Commentaires de rejet'),
        ),
    ]
