# Generated by Django 5.2.6 on 2025-09-08 11:24

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0019_notification_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Pays du projet'),
        ),
    ]
