# Generated by Django 5.2.6 on 2025-09-09 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0020_project_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField(blank=True, null=True, verbose_name="Description de l'avancement")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='task_photos/', verbose_name="Photo de l'avancement")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Rapporté par')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='intranet.task', verbose_name='Tâche associée')),
            ],
            options={
                'verbose_name': 'Rapport de Tâche',
                'verbose_name_plural': 'Rapports de Tâche',
                'ordering': ['-created_at'],
            },
        ),
    ]
