# Generated by Django 5.2.6 on 2025-09-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('intranet', '0021_taskreport'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='intranet_us_email_cb2fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'country'], name='intranet_us_is_acti_782210_idx'),
        ),
    ]
