# Generated by Django 5.2.6 on 2025-09-13 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0022_user_intranet_us_email_cb2fe0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_sites', to=settings.AUTH_USER_MODEL, verbose_name='Team Lead Assigné'),
        ),
    ]
