# Generated by Django 5.2.6 on 2025-09-17 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0023_site_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='antenna_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ANTENNA TYPE'),
        ),
        migrations.AddField(
            model_name='site',
            name='atp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ATP'),
        ),
        migrations.AddField(
            model_name='site',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BATCH'),
        ),
        migrations.AddField(
            model_name='site',
            name='bb_ml',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BB / ML'),
        ),
        migrations.AddField(
            model_name='site',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='COMMENT'),
        ),
        migrations.AddField(
            model_name='site',
            name='ehs_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='EHS 1'),
        ),
        migrations.AddField(
            model_name='site',
            name='ehs_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='EHS 2'),
        ),
        migrations.AddField(
            model_name='site',
            name='enclosure_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ENCLOSURE TYPE'),
        ),
        migrations.AddField(
            model_name='site',
            name='imk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IMK'),
        ),
        migrations.AddField(
            model_name='site',
            name='installation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='INSTALLATION'),
        ),
        migrations.AddField(
            model_name='site',
            name='integration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='INTEGRATION'),
        ),
        migrations.AddField(
            model_name='site',
            name='phase',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PHASE'),
        ),
        migrations.AddField(
            model_name='site',
            name='project_scope',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PROJET SCOPE'),
        ),
        migrations.AddField(
            model_name='site',
            name='qa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='QA'),
        ),
        migrations.AddField(
            model_name='site',
            name='qa_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='QA STATUT'),
        ),
        migrations.AddField(
            model_name='site',
            name='radio_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RADIO TYPE'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Site Area'),
        ),
        migrations.AddField(
            model_name='site',
            name='srs',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SRS'),
        ),
        migrations.AlterField(
            model_name='site',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='intranet.project', verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_id',
            field=models.CharField(default=0, max_length=100, unique=True, verbose_name='ID du Site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Team Lead Assigné'),
        ),
    ]
