# Generated by Django 5.2.6 on 2025-09-17 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0024_site_antenna_type_site_atp_site_batch_site_bb_ml_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntennaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BBML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnclosureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QAStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RadioType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='site',
            name='antenna_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.antennatype', verbose_name="Type d'antenne"),
        ),
        migrations.AlterField(
            model_name='site',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.batch', verbose_name='Batch'),
        ),
        migrations.AlterField(
            model_name='site',
            name='bb_ml',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.bbml', verbose_name='BB / ML'),
        ),
        migrations.AlterField(
            model_name='site',
            name='enclosure_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.enclosuretype', verbose_name='Type de boîtier'),
        ),
        migrations.AlterField(
            model_name='site',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.phase', verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='site',
            name='project_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.projectscope', verbose_name='Portée du projet'),
        ),
        migrations.AlterField(
            model_name='site',
            name='qa_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.qastatus', verbose_name='Statut QA'),
        ),
        migrations.AlterField(
            model_name='site',
            name='radio_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.radiotype', verbose_name='Type de radio'),
        ),
        migrations.AlterField(
            model_name='site',
            name='atp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atp_sites', to='intranet.sitestatus', verbose_name='ATP'),
        ),
        migrations.AlterField(
            model_name='site',
            name='ehs_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ehs1_sites', to='intranet.sitestatus', verbose_name='EHS 1'),
        ),
        migrations.AlterField(
            model_name='site',
            name='ehs_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ehs2_sites', to='intranet.sitestatus', verbose_name='EHS 2'),
        ),
        migrations.AlterField(
            model_name='site',
            name='imk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imk_sites', to='intranet.sitestatus', verbose_name='IMK'),
        ),
        migrations.AlterField(
            model_name='site',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_sites', to='intranet.sitestatus', verbose_name='Installation'),
        ),
        migrations.AlterField(
            model_name='site',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_sites', to='intranet.sitestatus', verbose_name='Intégration'),
        ),
        migrations.AlterField(
            model_name='site',
            name='qa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_sites', to='intranet.sitestatus', verbose_name='QA'),
        ),
        migrations.AlterField(
            model_name='site',
            name='srs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='srs_sites', to='intranet.sitestatus', verbose_name='SRS'),
        ),
    ]
