"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_7&zs^59@zv_r4ye%&i0y*)s3d$cnb2ecot#f6a*q&fq25x004'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '192.168.1.80',
    '192.168.1.74',
    'localhost',
    '127.0.0.1',
    # L'URL ngrok spécifique doit être incluse si tu l'utilises.
    # Assure-toi qu'elle correspond exactement à l'URL fournie par ngrok.
    '0999-2c0f-53c0-605-9a00-124a-d543-7c4e-c3e3.ngrok-free.app',
    # Ceci permet tous les sous-domaines de ngrok-free.app, utile si ton URL ngrok change.
    '.ngrok-free.app'
]


CSRF_TRUSTED_ORIGINS = [
    'http://192.168.1.80',
    'http://localhost',
    'http://127.0.0.1',
    # Pour ngrok, utilise toujours HTTPS car ngrok tunnelise vers HTTPS.
    'https://0999-2c0f-53c0-605-9a00-124a-d543-7c4e-c3e3.ngrok-free.app',
    'https://*.ngrok-free.app' # Permet tous les sous-domaines ngrok en HTTPS
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'intranet', # Notre application
    'crispy_forms', # Pour les formulaires
    'crispy_bootstrap5',  # NOUVEAU : Ajoutez le nouveau pack
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"  # NOUVEAU
CRISPY_TEMPLATE_PACK = "bootstrap5"           # NOUVEAU

# CRISPY_TEMPLATE_PACK = 'bootstrap4' # Utilisez ce pack pour un design moderne

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'intranet.context_processors.is_rh_group',
                'intranet.context_processors.is_project_coordinator', 
                'intranet.context_processors.unread_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] # CORRECTION
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')   # Recommandé pour la production

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
AUTH_USER_MODEL = 'intranet.User'
# URLs de connexion et de redirection après connexion
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGIN_REDIRECT_URL = 'home_view'
LOGOUT_REDIRECT_URL = 'login' # Redirection après déconnexion